### ISSUE TITLE
chart: make certificate issuer configurable

### ISSUE THREAD

**Issue by wrenix** [Intrinsec/s3proxy#9]

**Comment by rivoalrivoal** [comment]
Hi @wrenix, thank for your issue.
You talk about [this line](https://github.com/Intrinsec/s3proxy/blob/main/charts/s3proxy/templates/certificate.yaml#L12)  ?

**Comment by rivoalrivoal** [comment]
Added in https://github.com/Intrinsec/s3proxy/pull/16/files
